import { v4 as uuidv4 } from "uuid";
import Emirates from "../../assets/flight-listing/Emirates.png";
import FlyDubai from "../../assets/flight-listing/FlyDubai.png";
import Qatar from "../../assets/flight-listing/Qatar.png";
import Etihad from "../../assets/flight-listing/Etihad.png";

export const flightOptions = [
	{
		id: uuidv4(),
		image: Emirates,
		name: "Emirates A380 Airbus",
		rating: 4.8,
		reviewSummary: "Excellent",
		reviewCount: 120,
		price: 95,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:45am",
				airline: "Emirates",
				duration: "1h 45m",
				route: "JFK-BOS",
				nonStop: true,
			},
			{
				departureTime: "02:00pm",
				arrivalTime: "03:45pm",
				airline: "Emirates",
				duration: "1h 45m",
				route: "JFK-BOS",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: FlyDubai,
		name: "FlyDubai Premium Express",
		rating: 4.6,
		reviewSummary: "Very Good",
		reviewCount: 89,
		price: 140,
		currency: "USD",
		category: "Best",
		deals: [
			{
				departureTime: "09:30am",
				arrivalTime: "11:00am",
				airline: "Fly Dubai",
				duration: "1h 30m",
				route: "LAX-SFO",
				nonStop: true,
			},
			{
				departureTime: "04:15pm",
				arrivalTime: "05:45pm",
				airline: "Fly Dubai",
				duration: "1h 30m",
				route: "LAX-SFO",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: Qatar,
		name: "Qatar JetSpeed 300",
		rating: 3.9,
		reviewSummary: "Good",
		reviewCount: 64,
		price: 180,
		currency: "USD",
		category: "Quick",
		deals: [
			{
				departureTime: "07:15am",
				arrivalTime: "08:30am",
				airline: "Qatar Airways",
				duration: "1h 15m",
				route: "ATL-MIA",
				nonStop: true,
			},
			{
				departureTime: "01:00pm",
				arrivalTime: "02:15pm",
				airline: "Qatar Airways",
				duration: "1h 15m",
				route: "ATL-MIA",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: Etihad,
		name: "Etihad Skyline",
		rating: 4.1,
		reviewSummary: "Very Good",
		reviewCount: 70,
		price: 110,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "06:00am",
				arrivalTime: "07:50am",
				airline: "Delta",
				duration: "1h 50m",
				route: "EWR-BNA",
				nonStop: true,
			},
			{
				departureTime: "03:00pm",
				arrivalTime: "04:50pm",
				airline: "Delta",
				duration: "1h 50m",
				route: "EWR-BNA",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight5.jpg",
		name: "United Skypath 720",
		rating: 4.7,
		reviewSummary: "Excellent",
		reviewCount: 150,
		price: 200,
		currency: "USD",
		category: "Best",
		deals: [
			{
				departureTime: "10:00am",
				arrivalTime: "12:30pm",
				airline: "United",
				duration: "2h 30m",
				route: "SEA-DEN",
				nonStop: true,
			},
			{
				departureTime: "05:30pm",
				arrivalTime: "08:00pm",
				airline: "United",
				duration: "2h 30m",
				route: "SEA-DEN",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight6.jpg",
		name: "Southwest Budget Flyer",
		rating: 3.7,
		reviewSummary: "Decent",
		reviewCount: 45,
		price: 88,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "11:00am",
				arrivalTime: "12:45pm",
				airline: "Southwest",
				duration: "1h 45m",
				route: "PHX-LAS",
				nonStop: true,
			},
			{
				departureTime: "07:00pm",
				arrivalTime: "08:45pm",
				airline: "Southwest",
				duration: "1h 45m",
				route: "PHX-LAS",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight7.jpg",
		name: "Delta Urban Dash",
		rating: 4.0,
		reviewSummary: "Good",
		reviewCount: 68,
		price: 135,
		currency: "USD",
		category: "Quick",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:30am",
				airline: "Delta",
				duration: "1h 30m",
				route: "ORD-ATL",
				nonStop: true,
			},
			{
				departureTime: "03:00pm",
				arrivalTime: "04:30pm",
				airline: "Delta",
				duration: "1h 30m",
				route: "ORD-ATL",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight8.jpg",
		name: "Qatar Elite Wings",
		rating: 4.9,
		reviewSummary: "Excellent",
		reviewCount: 200,
		price: 215,
		currency: "USD",
		category: "Best",
		deals: [
			{
				departureTime: "06:30am",
				arrivalTime: "08:30am",
				airline: "Qatar Airways",
				duration: "2h 0m",
				route: "DFW-JFK",
				nonStop: true,
			},
			{
				departureTime: "06:30pm",
				arrivalTime: "08:30pm",
				airline: "Qatar Airways",
				duration: "2h 0m",
				route: "DFW-JFK",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight9.jpg",
		name: "Spirit Value Hopper",
		rating: 3.8,
		reviewSummary: "Average",
		reviewCount: 58,
		price: 99,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "09:00am",
				arrivalTime: "10:40am",
				airline: "Spirit",
				duration: "1h 40m",
				route: "CLT-DCA",
				nonStop: true,
			},
			{
				departureTime: "01:30pm",
				arrivalTime: "03:10pm",
				airline: "Spirit",
				duration: "1h 40m",
				route: "CLT-DCA",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight10.jpg",
		name: "Alaska Coastal Glide",
		rating: 4.3,
		reviewSummary: "Very Good",
		reviewCount: 112,
		price: 175,
		currency: "USD",
		category: "Quick",
		deals: [
			{
				departureTime: "07:45am",
				arrivalTime: "09:15am",
				airline: "Alaska Airlines",
				duration: "1h 30m",
				route: "SFO-LAX",
				nonStop: true,
			},
			{
				departureTime: "05:00pm",
				arrivalTime: "06:30pm",
				airline: "Alaska Airlines",
				duration: "1h 30m",
				route: "SFO-LAX",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight11.jpg",
		name: "JetBlue Special 1",
		rating: 4.0,
		reviewSummary: "Good",
		reviewCount: 85,
		price: 152,
		currency: "USD",
		category: "Quick",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "JetBlue",
				duration: "1h 20m",
				route: "BOS-PHL",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "JetBlue",
				duration: "1h 20m",
				route: "BOS-PHL",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight12.jpg",
		name: "American Airlines Special 2",
		rating: 3.6,
		reviewSummary: "Average",
		reviewCount: 74,
		price: 106,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "American Airlines",
				duration: "1h 25m",
				route: "SJC-SAN",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "American Airlines",
				duration: "1h 25m",
				route: "SJC-SAN",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight13.jpg",
		name: "Hawaiian Airlines Special 3",
		rating: 3.7,
		reviewSummary: "Decent",
		reviewCount: 84,
		price: 119,
		currency: "USD",
		category: "Quick",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Hawaiian Airlines",
				duration: "45m",
				route: "HNL-OGG",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Hawaiian Airlines",
				duration: "45m",
				route: "HNL-OGG",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight14.jpg",
		name: "Frontier Special 4",
		rating: 4.7,
		reviewSummary: "Excellent",
		reviewCount: 145,
		price: 179,
		currency: "USD",
		category: "Quick",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Frontier",
				duration: "1h 10m",
				route: "LAS-SLC",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Frontier",
				duration: "1h 10m",
				route: "LAS-SLC",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight15.jpg",
		name: "Jetstar Special 5",
		rating: 4.8,
		reviewSummary: "Excellent",
		reviewCount: 170,
		price: 102,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Jetstar",
				duration: "1h 0m",
				route: "MCO-TPA",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Jetstar",
				duration: "1h 0m",
				route: "MCO-TPA",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight16.jpg",
		name: "Allegiant Special 6",
		rating: 3.9,
		reviewSummary: "Good",
		reviewCount: 111,
		price: 170,
		currency: "USD",
		category: "Best",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Allegiant",
				duration: "1h 15m",
				route: "TUL-DAL",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Allegiant",
				duration: "1h 15m",
				route: "TUL-DAL",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight17.jpg",
		name: "Norwegian Special 7",
		rating: 4.3,
		reviewSummary: "Very Good",
		reviewCount: 135,
		price: 203,
		currency: "USD",
		category: "Best",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Norwegian",
				duration: "1h 30m",
				route: "EWR-YYZ",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Norwegian",
				duration: "1h 30m",
				route: "EWR-YYZ",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight18.jpg",
		name: "Scoot Special 8",
		rating: 4.6,
		reviewSummary: "Very Good",
		reviewCount: 198,
		price: 106,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Scoot",
				duration: "1h 5m",
				route: "SEA-YVR",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Scoot",
				duration: "1h 5m",
				route: "SEA-YVR",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight19.jpg",
		name: "Volaris Special 9",
		rating: 3.7,
		reviewSummary: "Decent",
		reviewCount: 180,
		price: 105,
		currency: "USD",
		category: "Cheap",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Volaris",
				duration: "2h 5m",
				route: "LAX-SJD",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Volaris",
				duration: "2h 5m",
				route: "LAX-SJD",
				nonStop: true,
			},
		],
	},
	{
		id: uuidv4(),
		image: "/images/flight20.jpg",
		name: "Avianca Special 10",
		rating: 4.2,
		reviewSummary: "Very Good",
		reviewCount: 70,
		price: 215,
		currency: "USD",
		category: "Best",
		deals: [
			{
				departureTime: "08:00am",
				arrivalTime: "09:20am",
				airline: "Avianca",
				duration: "2h 20m",
				route: "IAH-MEX",
				nonStop: true,
			},
			{
				departureTime: "04:00pm",
				arrivalTime: "05:20pm",
				airline: "Avianca",
				duration: "2h 20m",
				route: "IAH-MEX",
				nonStop: true,
			},
		],
	},
];
